repos:
  -   repo: https://github.com/asottile/reorder_python_imports
      rev: v3.9.0
      hooks:
      -   id: reorder-python-imports
          args: [--py37-plus, --add-import, 'from __future__ import annotations']
