# If desired, you can reference this file with --yaml flag
# and have the properties / flags automatically set

name: helloFunction
file: app.zip
handler: 'app.hello'
inputParams: ''
returnType: string
overwrite: true
# database: myDatabase
# schema: mySchema
# role: myRole
# warehouse: myWarehouse
